export const LOGIN = 'LOGIN';
export const SET_TOKEN = 'SET_TOKEN';
export const DEL_TOKEN = 'DEL_TOKEN';
export const SET_TOKEN_STATUS = 'SET_TOKEN_STATUS';

export const SET_USER_MAIN_DATA = 'SET_USER_MAIN_DATA';
export const SET_USER_ADDITIONAL_DATA = 'SET_USER_ADDITIONAL_DATA';
export const SET_USER_SETTINGS_DATA = 'SET_USER_SETTINGS_DATA';
export const UPDATE_USER_SETTINGS_DATA = 'UPDATE_USER_SETTINGS_DATA';
export const SET_USER_MASTER_ACCOUNT_DATA = 'SET_USER_MASTER_ACCOUNT_DATA';

export const SET_CURRENT_TAX_DATA = 'SET_CURRENT_TAX_DATA';
export const SET_ALL_TAX_DATA = 'SET_ALL_TAX_DATA';

export const SET_METER_DATA = 'SET_METER_DATA';
export const SET_METER_HISTORY_DATA = 'SET_METER_HISTORY_DATA';

export const SET_NEWS_DATA = 'SET_NEWS_DATA';

export const SET_IDEAS_DATA = 'SET_IDEAS_DATA';
export const REMOVE_IDEAS_DATA = 'REMOVE_IDEAS_DATA';

export const SET_VOTES_DATA = 'SET_VOTES_DATA';
export const SET_VOTES_QUESTIONS_DATA = 'SET_VOTES_QUESTIONS_DATA';

export const SET_CONTACTS_DATA = 'SET_CONTACTS_DATA';
export const SET_SERVICE_PROVIDERS_DATA = 'SET_SERVICE_PROVIDERS_DATA';
export const SET_PARTNERS_DATA = 'SET_PARTNERS_DATA';

export const SET_DOCS_DATA = 'SET_DOCS_DATA';

export const SET_FINANCES_DATA = 'SET_FINANCES_DATA';

export const SET_TASKS_DATA = 'SET_TASKS_DATA';

export const SET_NOTES_DATA = 'SET_NOTES_DATA';

export const SET_SMS_DATA = 'SET_SMS_DATA';
export const SET_SMS_CREDIT_DATA = 'SET_SMS_CREDIT_DATA';
export const SET_SMS_RECIPIENT_DATA = 'SET_SMS_RECIPIENT_DATA';

export const SET_EMAIL_DATA = 'SET_EMAIL_DATA';
export const SET_EMAIL_RECIPIENT_DATA = 'SET_EMAIL_RECIPIENT_DATA';

export const SET_INVOICES_DATA = 'SET_INVOICES_DATA';
export const SET_STATEMENTS_DATA = 'SET_STATEMENTS_DATA';

export const SET_OWNERS_DATA = 'SET_OWNERS_DATA';
export const SET_DEBTORS_DATA = 'SET_DEBTORS_DATA';

export const RESET_USER_DATA = 'RESET_USER_DATA';

